version: "3.4"

services:
  nginx:
    restart: always
    image: ghcr.io/qchateau/space-dodgems-client:latest
    ports:
      - "${EXTERNAL_PORT-127.0.0.1:8081}:80"
    environment:
      - WS_SERVER=backend:5678

  backend:
    restart: always
    image: ghcr.io/qchateau/space-dodgems-server:latest
    environment:
      - ADDR=0.0.0.0
      - PORT=5678
      - NWORLDS=${NWORLDS-10}
