version: "3.4"

volumes:
  conandata:
  builddata:

services:
  nginx:
    build:
      context: ./client
    volumes:
      - ./nginx:/etc/nginx/templates
      - ./client:/www/data
  backend:
    build:
      context: ./server
      target: dev
    volumes:
      - ./server/:/opt/server/
      - conandata:/root/.conan/
      - builddata:/opt/server/build/
